### ISSUE TITLE
/list route not usable

### ISSUE THREAD

**Issue by yizhao1998** [UltiRequiem/copero#10]
Hi Eliaz, thanks for providing this open source project.
The [See all public snippets...](https://copero.vercel.app/list) link in index page requests to the `/api/all`, and calling mongoDB `find` method underneath. The code requests `find` method with `private` parameter, which was not defined in the `Snippet` schema, I highly suggest remove this Link.

**Comment by UltiRequiem** [comment]
Thanks!

It used to be working if I remember correctly, I will try to fix it instead of removing it all, i liked this feature.

**Comment by UltiRequiem** [comment]
Now it works! I will probably redo this app when I have time (in a few years again probably) because the style sucks. But it's working at least! Anyone is free to PR lol
